<?php
$translate = $this->plugin('translate');
?>
<?php $this->htmlElement('body')->appendAttribute('class', 'media resource show'); ?>
<div class="dh-media-show">
    <?php echo $this->pageTitle($media->displayTitle(), 2); ?>
    <h3><?php echo $translate('Media'); ?></h3>
    <?php $this->trigger('view.show.before'); ?>
    <?php echo $media->render(); ?>
    <?php echo $media->displayValues(); ?>
</div>
<?php $this->trigger('view.show.after'); ?>
